### ISSUE TITLE
dat fiind ca e la fel, poti face un @BeforeAll sau @BeforeEach sau sa pun intr-o metoda

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#1]
https://github.com/cezarhre/curs17.homework/blob/621d6e607ec1c02edd1bc54ae75ffcba40de706a/src/test/java/ro/fasttrackit/curs17/homework/PersonServiceTest.java#L211

**Comment by cezarhre** [comment]
Nu mai e la fel
