### ISSUE TITLE
record-ul iti pune by default equals, hashcode si tostring. Nu e nevoie sa le suprascrii decat daca ai motive bine argumentate

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#10]
https://github.com/cezarhre/curs17.homework/blob/9bb6050861a5912d46782797801e23d5f01c600f/src/main/java/ro/fasttrackit/curs17/homework/Person.java#L36

**Comment by cezarhre** [comment]
Au ramas dupa ce am facut record... Le-am sters
