### ISSUE TITLE
asta ti-a ramas de data trecuta. Nu are nicio valoare sa compari rezultatul metodei cu el insusi.. va fi tot timpul ok

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#13]
https://github.com/cezarhre/curs17.homework/blob/9bb6050861a5912d46782797801e23d5f01c600f/src/test/java/ro/fasttrackit/curs17/homework/PersonServiceTest.java#L104

**Comment by cezarhre** [comment]
Am refacut
