### ISSUE TITLE
trebuia sa te asiguri in constructor ca nu sunt null-uri in lista

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#16]
https://github.com/cezarhre/curs17.homework/blob/228a97b9f3d748979a340e60dead5405b4aac507/src/main/java/ro/fasttrackit/curs17/homework/PersonService.java#L20

**Comment by cezarhre** [comment]
m-am asigurat...
persons == null || persons.isEmpty()
                ? new ArrayList<>()
                : new ArrayList<>(persons);

nu e OK?
