### ISSUE TITLE
Not a valid name nu e un nume frumos... arunca exceptie sau lasa gol... dar nu punem mesaje de eroare in nume

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#17]
https://github.com/cezarhre/curs17.homework/blob/228a97b9f3d748979a340e60dead5405b4aac507/src/main/java/ro/fasttrackit/curs17/homework/Person.java#L13

**Comment by cezarhre** [comment]
Am rectificat
