### ISSUE TITLE
cand e accelasi obiect in assertThat()... continua asserturile. isNotNull().isEqualTo().. evident cu enter inainte de .

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs17.homework#2]
https://github.com/cezarhre/curs17.homework/blob/621d6e607ec1c02edd1bc54ae75ffcba40de706a/src/test/java/ro/fasttrackit/curs17/homework/PersonServiceTest.java#L150

**Comment by cezarhre** [comment]
Am facut
